### ISSUE TITLE
Fix "Run a URL" screen saver

### ISSUE THREAD

**Issue by jesseolsen** [muffinista/before-dawn#135]
I have tried different urls for the "Run a URL" screensaver, but they all just show a black screen.  I then saw on this page that they were unsuccessful as well: https://www.ghacks.net/2021/02/11/before-dawn-is-an-open-source-program-that-has-many-cool-screensavers/

What "load_url" should I use?

![image](https://user-images.githubusercontent.com/6043493/155666103-984f31c8-ce14-48c1-be56-97a1c2a5cd90.png)

**Comment by muffinista** [comment]
Hi @jesseolsen thanks for reporting this! I just pushed out a new release that should fix this problem.
