### ISSUE TITLE
Run A URL problem

### ISSUE THREAD

**Issue by bobtb98** [muffinista/before-dawn#138]
From 1 of the closed issues, I've notice the same problem happening to me. When I tried the function "Run A URL" it shows a black screen instead of a webpage. I've tested with both "https://www.google.com/" and "https://www.airbnb.com"

**Comment by muffinista** [comment]
Thanks for pointing this out! Should be fixed by https://github.com/muffinista/before-dawn/releases/tag/v0.18.6

**Comment by bobtb98** [comment]
I've tested the "Run a URL" function, it is working flawlessly
