### ISSUE TITLE
Failed to load screenshot

### ISSUE THREAD

**Issue by kuroismith** [muffinista/before-dawn#15]
hi, 

I wrote a screensaver myself [vino](https://github.com/kuroismith/before-dawn-screensavers/blob/master/vino/). I use p5.js instead of processing.js. The screenshot is loaded as the backgroud. It works pretty well in preview mode, but it failed to load the screenshot when actually running it.
I use macos 10.14.3.

Btw I love this app, thanks a lot.

**Comment by kuroismith** [comment]
I test it on my win10 laptop but the app itself failed to launch.

**Comment by muffinista** [comment]
Hi! I think I see two issues. First, in `savers.json`, either remove:

```
  "requirements": [
    "none"
  ],
```
 or change it from 'none' to 'screen'

Second, in `vino.js`, the image will load if you change this line:

```
  img = loadImage(decodeURIComponent(window.urlParams.screenshot));   
```

```
  img = loadImage(unescape(decodeURIComponent(window.urlParams.screenshot)));   
```

The first issue is something I really need to document properly, sorry about that! The second issue is really a bug in Before Dawn as well -- I really need to make loading that image URL a lot easier, so I might change how this works in the future, but for the moment adding `unescape` should work for you.

**Comment by kuroismith** [comment]
It works, thank you for your help.

**Comment by kuroismith** [comment]
Another question, the screenshot is a little bit low quality. Is there any chance to get a higher quality screenshot?

**Comment by muffinista** [comment]
@kuroismith the screenshot should be the same resolution as your monitor. Can you let me know if you're using a 4k device or something like that? It's possible the math is wrong.

**Comment by kuroismith** [comment]
It seems more likely to be an image compression issue. I'll look into the resolution of the screenshot and let you know.

**Comment by kuroismith** [comment]
the size of screenshot is 1440 * 900, exactly the same with my display device.
it seems more likely to be a image compression issue to me

**Comment by muffinista** [comment]
I've tweaked the code to ensure that the screenshot isn't compressed, although I don't think I ever actually experienced this. Anyway, if it still looks bad definitely let me know.
