### ISSUE TITLE
Random Screen Saver

### ISSUE THREAD

**Issue by martiniturbide** [muffinista/before-dawn#190]
Hello

I'm having fun with "Before Dawn" here. !

Is there a way to select a "Random" or "Radomizer" screensaver that runs any screensaver from list?

Regards

**Comment by muffinista** [comment]
Hi there, thanks for asking! There is a random screensaver, but it wasn't appearing in the list. I just fixed that so it should be in the newest update.

**Comment by martiniturbide** [comment]
Thanks !!!!
