### ISSUE TITLE
Support for After Dark Modules

### ISSUE THREAD

**Issue by martiniturbide** [muffinista/before-dawn#193]
Hello Colin

This is just a crazy idea that I want to discuss/brain storm.  
Do you think that it can be possible for "Before Dawn" to support "After Dark" (AD) screen savers. 

For example, if we have the AD module files for "The Simpsons" edition. Can it be possible to run those module screen saver over "Before Dawn"?

But I guess there are some issues here:
1) The AD modules are not standardized, I think they changed over time with the different AD versions. So one size will not fit all.
2) I think that AD modules are just programs developed for a specific operating system, and are not OS independent. Right?

What do you think? too crazy?

Regards
Martin

**Comment by jmfergeau** [comment]
I'm still relatively new to nodejs and i don't know much about bigger languages around but I feel like it would be a crazy ammount of work indeed.

I'm pretty sure After Dark screensavers are binaries, probably coded in a specific way to work with After Dark only, which was a closed source screensaver system. That would require reverse-engineering something that was probably written in C or derivatives then make nodejs translate them. And as you said, the screensavers certainly differs from a version to another and from an os to another...

Our dev here will surely tell us more, but i'm pretty sure it's not really possible. Or if it is, it would take yearsand huge work, especially for just one dev.

**Comment by muffinista** [comment]
I certainly love the idea, but it would be pretty challenging. I haven't looked too closely, but AD screensavers were definitely closed source, and were probably compiled binaries of some sort (if I remember right, on Windows you can literally change any .SCR file into a .EXE file and run it like a normal program). Ironically the easiest way to run one would probably be to try and integrate a javascript DOS/windows emulator, and try to run a saver via that code. But that's before even considering the licensing issues/etc. Someone (I think Microsoft?) owns the rights to those screensavers, and lots of people have definitely been sued for copying the Flying Toasters screensaver back in the day.

**Comment by martiniturbide** [comment]
Thanks for the feedback.

From the licensing point of view, the idea will not be to include proprietary binaries or source code to "Before Dawn", but to create the interpreter for people that own AD screensavers can copy the module to run it on "Before Dawn", just like an emulator does these days. Maybe the licensing issue consideration that should be taken care is being sure that the open source javascript DOS/windows emulator to run the Windows executable (AD module) does not break any copyright. 

But again, from the technical side of the idea. Is there any open source javacript Win16 API clone project, that can be cornerstone to run an AD module or even After Dark? I mean Win16, since I guess it will be easier for the moment. Or maybe just going after Wine project?

Please remember that this is only a brainstorming. 

Regards.
