### ISSUE TITLE
System tray icon not appearing on KDE 6

### ISSUE THREAD

**Issue by jmfergeau** [muffinista/before-dawn#194]
As title says. When program is launched, no icon appears while it is appearing as running in the processes list.

I suspect it's happening because of KDE's recent update to the 6. Some system tray icons got some problems, probably because they changed something so maybe it's related?

**Comment by MubarakHAlketbi** [comment]
having the same issue with windows 11 and v0.29, going back to v0.28 and facing no issues.

**Comment by muffinista** [comment]
Oops, I see the problem, will try and fix today.

**Comment by jmfergeau** [comment]
Works great indeed ^^ ~~tho, since the icon is black, it might become invisible if the DE is in dark mode. I'm not sure there's a way to set a dark mode version of the icon, but if yes, it would be good to add one ^^~~

I made some researches and it seems you already did the stuff for dark theme tray icons. I guess it's just KDE not understanding how these works. Poo... :sweat_smile:
