### ISSUE TITLE
Contribution: Pixel Fireplace?

### ISSUE THREAD

**Issue by lexterror** [muffinista/before-dawn#197]
Hi, I recently created a Pixel Fireplace! If you think it's appropriate for your project let me know:

Live preview:

https://js-pixel-fireplace.sourceforge.io/fireplace.html

Source code:

https://github.com/lexterror/8-bit-pixel-fireplace-android-linux

Thank you!

**Comment by muffinista** [comment]
Hi @lexterror I think it's totally appropriate! If you'd like it to be a part of the project, you could open a PR over at [before-dawn-screensavers](https://github.com/muffinista/before-dawn-screensavers/). Thank you!

**Comment by lexterror** [comment]
Hi @muffinista 

I just finished tweaking the fireplace, there's so many possibilities as to what you can add/build with any coding language. Umm.. I really don't have anyone to give me feedback (How does the fireplace look to you from what you saw last time) Only if you have time. I understand you may be busy. I adjusted and added many things but you'd have to have attention to detail as they say. And maybe even take 2 minutes to observe the differences. I wanted something fancier that's all. I'm trying read the README you have posted in the contribution section. Give me some time. I would like to include it if you think it's good enough or whatever. Thank you

**Comment by lexterror** [comment]
@muffinista 

Hi, I've made some major improvements to the Pixel Fireplace and Im feeling confident. 
I'm attaching my template. Please get back to me. If you need further information, etc, let me know. 

[template_YuleLogEd.zip](https://github.com/muffinista/before-dawn/files/15006934/template_YuleLogEd.zip)


Thank you!

**Comment by muffinista** [comment]
Sorry for the delay, I just opened a PR to add the screensaver at https://github.com/muffinista/before-dawn-screensavers/pull/21 -- @lexterror please let me know if you're cool with that. Thanks!
