### ISSUE TITLE
Doesn't work on MacOS after version 0.9.12

### ISSUE THREAD

**Issue by richardmalone** [muffinista/before-dawn#2]
The errors change a bit depending on which version I try. On 0.9.16 the error I get when running from the terminal is:

[12:19:25.212] [info] Setup sentry logging with https://b86f7b0ac5604b55b4fd03adedc5d205:9cc446fadc234baab6d825e88fe4215d@sentry.io/172824
[12:19:25.218] [info] Running in production
[12:19:25.405] [info] Load config with { base: '/Users/lucky/Library/Application Support/Before Dawn',
  systemDir: '/Applications/Before Dawn.app/Contents/Resources/app/output' }
raven@2.3.0 alert: unhandledRejection captured: 55793aedb64045db8676b7bcb7d02684

My machine is High Sierra. 0.9.12 loads fine.

Thanks for your great app!

**Comment by muffinista** [comment]
Thanks for the bug report! Are you running a screensaver you wrote yourself by any chance? I'm going to add some more debugging output to see if that helps as well.

**Comment by richardmalone** [comment]
No problem!

I did previously have a custom screensaver, but I deleted the ~/Library/Application Support/Before Dawn and it still gave me the error.

I think that has wiped all my previous settings.

**Comment by muffinista** [comment]
OK, thanks for the info! I'm not entirely sure what is going wrong, but I've just pushed a new release which might help with the issue, and if not, should log some additional info. It should be available [here](https://github.com/muffinista/before-dawn/releases/tag/v0.9.17)

**Comment by richardmalone** [comment]
That seems to work for me. Thanks!

Any chance you can invert the colours on the taskbar icon? Otherwise it is sort of transparent on Mac OS.

**Comment by muffinista** [comment]
I'll keep that in mind. Thanks for the feedback!
