### ISSUE TITLE
[deb package] savers folder not included

### ISSUE THREAD

**Issue by jmfergeau** [muffinista/before-dawn#201]
In the deb package, the folder `opt/Before Dawn/resources/savers` doesn't exist, unlike older version packages. Is it intended?

**Comment by muffinista** [comment]
Sorry! [This release](https://github.com/muffinista/before-dawn/releases/tag/v0.30.1) hopefully fixes that.

**Comment by jmfergeau** [comment]
Thanks :)

I just noticed cloning from the repo doesn't give the savers either. Am I missing something?

**Comment by muffinista** [comment]
They're in a separate repo over at [before-dawn-screensavers](https://github.com/muffinista/before-dawn-screensavers/). If you're running the code locally, you can clone that repo too and point to it with the 'local folder' setting.
