### ISSUE TITLE
Screen does not lock on Ubuntu

### ISSUE THREAD

**Issue by vincerubinetti** [muffinista/before-dawn#32]
The computer lock function doesn't seem to work on Ubuntu 18+. Happy to help you debug this issue as well, as this might be a discouragement for people to use the screensaver in my office.

xScreensaver for Ubtuntu seems to have the same problem, and seems to have to implement its own lock functionality (which is an ugly solution). So it might not be an easy problem to fix.

**Comment by muffinista** [comment]
This is a hard one to fix but there's a chance the most recent release will help with it.

**Comment by vincerubinetti** [comment]
Yeah researching this a bit it seems like there's no standard way to lock the screen on Ubuntu. I'm still fairly new to Linux, but it seems like there's not only different flavors of Linux, but also different Linux desktops like Gnome and Unity, which presumably each do things a little differently.

---

I wonder, is it possible to have the software run an arbitrary command line command when a screensaver is exited? Not sure if Electron supports that. If it were possible, users would just need to figure out a way to lock the screen with a command. On my version of Ubuntu and Gnome, it looks like that would be accomplished by installing `gnome-screensaver` and then running `gnome-screensaver-command -l`

**Comment by muffinista** [comment]
That's definitely an interesting idea. I'll add it to my todo list.
