### ISSUE TITLE
Very unstable on windows

### ISSUE THREAD

**Issue by jmfergeau** [muffinista/before-dawn#47]
First, thanks alot for this software. You realized one of my dreams. :)

For some reason, I can't get Before Dawn to really work.

I'm trying to test out a default screensaver (the Emoji fireplace for instance) by using the "run now" command (since it seems to be the only way to try out a saver) The saver launches as expected, but  when it stops, before dawn becomes a zombie process, freezing completely (even the settings windows) and forcing me to kill the process.

Also tried with a fresh screensaver I made and this one doesn't even start. It directly freezes the program. Though, it animates perfectly as expected in the preview.

Is there a way to enable a debug mode on the release versions so I can maybe find out what goes wrong? I'm on Windows 10. Tested on the latest release of BD, 0.11.7

Thanks

**Comment by muffinista** [comment]
Hi @maxlefou, I see what you're saying! Apparently I didn't do a good enough job of testing the latest release on Windows. There's not really a debug mode, although you can always download the codebase and run it if you're comfortable with that. But I will spend a little time focusing on the Windows build and see if I can take care of some obvious problems. Thanks!

**Comment by jmfergeau** [comment]
Thanks for heads up :) sadly i'm still a beginner in electron apps so i'm not sure i can help by more than just reporting errors. Feel free to ask if i can provide you any more helpful infos though. :)

**Comment by jmfergeau** [comment]
closing up since it all works fine with the new 0.12.1 release. Thanks ^^

**Comment by muffinista** [comment]
That's great, thanks for the bug report!
