### ISSUE TITLE
Going to Standby even when set to never

### ISSUE THREAD

**Issue by richardmalone** [muffinista/before-dawn#64]
Hi, great software!

I am finding that if I set Sleep After to be Never, the computer goes to sleep immediately after the screensaver launches.

Windows 10, latest version.

![image](https://user-images.githubusercontent.com/6492842/95057782-877c8580-06ee-11eb-8aff-ac64a54d4400.png)

**Comment by muffinista** [comment]
Thanks for pointing out! Should be fixed with the next release in the next week or two.
