### ISSUE TITLE
Navbar with app sometimes visible when launching screensaver

### ISSUE THREAD

**Issue by AltoBluedot** [muffinista/before-dawn#74]
Sometimes the windows navbar with the blinking Before Dawn screensaver icon remains when the screensaver launches. This does not break the functionality, however it is a small bug that might require fixing.

**Comment by AltoBluedot** [comment]
It appears this bug occurs most often when no window is focused (so after clicking Super+D for instance to focus desktop).

**Comment by muffinista** [comment]
Thanks for pointing this out! I've seen this before but it's very hard to replicate, and I'm usually on an OSX box where this isn't happening. Anyway, I've pushed a release with a few changes that might help with this if you want to give it a try.
