### ISSUE TITLE
Shows empty on Windows

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [muffinista/before-dawn#80]
I am running Windows 10 Enterprise 1803:

![image](https://user-images.githubusercontent.com/46422834/107700671-d7dba380-6cdd-11eb-83b5-e713bfd0853a.png)

**Comment by muffinista** [comment]
Thanks for letting me know! I just put a release here: https://github.com/muffinista/before-dawn/releases/tag/v0.14.2 if you wouldn't mind trying that, I think it will fix the problem. It's possible you will need to open 'Advanced Settings' and then click 'Reset defaults'.

**Comment by Gaurav-Original-ClassicShellTester** [comment]
Yes indeedy! It fixed it! Thank you so much! I didn't even need to click Reset defaults.
